### ISSUE TITLE
Name the printed file

### ISSUE THREAD

**Issue by ponsfrilus** [Azecko/rapport-de-stage#50]
When printing a rapport, the default name is "Rapport de stage.pdf":
![image](https://github.com/Azecko/rapport-de-stage/assets/176002/6e68c3c7-d23b-4ab4-85cb-f90d74c7edfc)

It take the page's title. See https://stackoverflow.com/a/10189687/960623 on how to redefine it when printing.

I would propose:
- Prenom_Nom_Rapport_de_stage_responsables_EPFL_septembre_2023.pdf
- Prenom_Nom_Rapport_de_stage_stagiaire_EPFL_septembre_2023.pdf

Where Prenom and Nom add `-` instead of spaces.

**Comment by Azecko** [comment]
closed by f1dc28c7265cd8c14891890aca08086e6882c369
